### ISSUE TITLE
[编译报错] 'getter for opacity: Int' is deprecated.

### ISSUE THREAD

**Issue by starock** [howshea/RoundCornerImageView#1]
// 取 drawable 的颜色格式
val config = if (this.opacity != PixelFormat.OPAQUE)

这句代码编译的时候报错：
 'getter for opacity: Int' is deprecated. Deprecated in Java

this.opacity 的opacity已经被弃用，不知道用什么替换一下？

**Comment by howshea** [comment]
看了一下源码，Drawable 的 getOpacity() 在 API 28 还没有 deprecated 的注解，而且就算方法过时了也不会报错，最多就是个警告。

**Comment by starock** [comment]
谢谢，可能是我用kotlin的缘故吧。
